const data = {
  users: [
    {
      name: 'John',
      email: 'user@example.com',
      password: 12234,
      isAdmin: true,
    },
  ],

  products: [
    {
      // _id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', //679px x 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      //_id: '2',
      name: 'Adidas Fit shirt',
      slug: 'Adidas-Fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-Pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      //  _id: '4',
      name: 'Adidas Fit Pants',
      slug: 'Adidas-Fit-Pants',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '5',
      name: 'iPhone 14 Pro Max',
      slug: 'iPhone-14-Pro-Max',
      category: 'Mobile Phone',
      image: '/images/p5.jpg',
      price: 1099,
      countInStock: 5,
      brand: 'Apple',
      rating: 5,
      numReviews: 12,
      description: '5G network ',
    },
    {
      // _id: '6',
      name: 'Galaxy s22 Ultra',
      slug: 'galaxy-s22-ultra',
      category: 'Mobile Phone',
      image: '/images/p6.jpg',
      price: 1099,
      countInStock: 5,
      brand: 'Samsung',
      rating: 5,
      numReviews: 12,
      description: '5G network ',
    },
  ],
};

export default data;
